// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PlayStationSharp.Model.Ps5DevicesModelJsonTypes;

namespace PlayStationSharp.Model.Ps5DevicesModelJsonTypes
{

    public class Device
    {

        [JsonProperty("language")]
        public string Language { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("updatedDateTime")]
        public string UpdatedDateTime { get; set; }
    }

    public class Client
    {

        [JsonProperty("device")]
        public Device Device { get; set; }

        [JsonProperty("duid")]
        public string Duid { get; set; }

        [JsonProperty("platform")]
        public string Platform { get; set; }

        [JsonProperty("updatedDateTime")]
        public string UpdatedDateTime { get; set; }
    }

}

namespace PlayStationSharp.Model
{

    public class Ps5DevicesModel
    {

        [JsonProperty("clients")]
        public IList<Client> Clients { get; set; }
    }

}